/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.ups.vista;

import gnu.io.NRSerialPort;
import gnu.io.SerialPortEvent;
import gnu.io.SerialPortEventListener;
import java.io.DataInputStream;
import java.io.OutputStream;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import panamahitek.Arduino.PanamaHitek_Arduino;

/**
 *
 * @author Domenica Cañizares y Byron Vasquez
 */
public class Interfaz extends javax.swing.JFrame implements SerialPortEventListener {

    int r = 0;
    PanamaHitek_Arduino arduino = new PanamaHitek_Arduino();
    int OutputR;

    public void Led() {

        r = jSlider.getValue();

    }

    public void SetData() {

        //OutputR = "c";
        if (r >= 0 || r <= 400) {
            OutputR = 100;
        } else if (r >= 401 || r <= 600) {
            OutputR = 300;
        } else if (r >= 601 || r <= 800) {
            OutputR = 700;
        } else if (r >= 801) {
            OutputR = 1000;
        }

    }

    private NRSerialPort puertoUSB;

    /**
     * Creates new form Interfaz
     */
    public Interfaz() {
        initComponents();
        try {
            arduino.arduinoTX("COM13", 9600);

        } catch (Exception ex) {
            ex.printStackTrace();
        }

        //jSlider.setEnabled(false);
    }

    public void conectar() {
        try {

            estado.setText("Conexion Exitosa!!");
        } catch (Exception err) {
            err.printStackTrace();
        }
    }

    public void desconectar() {
        try {

            estado.setText("Desconectado");
        } catch (Exception err) {
            err.printStackTrace();
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn1Az = new javax.swing.JButton();
        btn2Am = new javax.swing.JButton();
        btn3Ro = new javax.swing.JButton();
        btn4Ver = new javax.swing.JButton();
        btn5Ro = new javax.swing.JButton();
        btn6Am = new javax.swing.JButton();
        btn7Az = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        btnConectar = new javax.swing.JButton();
        btnDesc = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        estado = new javax.swing.JLabel();
        jSlider = new javax.swing.JSlider();
        jPos = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btn1Az.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        btn1Az.setText("1 Azul");
        btn1Az.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1AzActionPerformed(evt);
            }
        });

        btn2Am.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        btn2Am.setText("2 Amarillo");
        btn2Am.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2AmActionPerformed(evt);
            }
        });

        btn3Ro.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        btn3Ro.setText("3 Rojo");
        btn3Ro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3RoActionPerformed(evt);
            }
        });

        btn4Ver.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        btn4Ver.setText("4 Verde");
        btn4Ver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4VerActionPerformed(evt);
            }
        });

        btn5Ro.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        btn5Ro.setText("5 Rojo");
        btn5Ro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn5RoActionPerformed(evt);
            }
        });

        btn6Am.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        btn6Am.setText("6 Amarillo");
        btn6Am.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn6AmActionPerformed(evt);
            }
        });

        btn7Az.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        btn7Az.setText("7 Azul");
        btn7Az.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn7AzActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Rockwell", 3, 36)); // NOI18N
        jLabel1.setText("Conexion Arduino");

        jButton8.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        jButton8.setText("EFECTO LÍNEA");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        jButton9.setText("EFECTO AUTO FANTASTICO");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton10.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        jButton10.setText("EFECTO NUEVO");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jButton11.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        jButton11.setText("DETENER EFECTOS");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jButton12.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        jButton12.setText("APAGAR LEDS");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        btnConectar.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        btnConectar.setText("Conectar Arduino");
        btnConectar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConectarActionPerformed(evt);
            }
        });

        btnDesc.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        btnDesc.setText("Desconectar Arduino");
        btnDesc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDescActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Estado Arduino");

        estado.setFont(new java.awt.Font("Rockwell", 2, 18)); // NOI18N
        estado.setText("Desconectado");

        jSlider.setForeground(new java.awt.Color(0, 102, 153));
        jSlider.setMajorTickSpacing(200);
        jSlider.setMaximum(1020);
        jSlider.setOrientation(javax.swing.JSlider.VERTICAL);
        jSlider.setPaintLabels(true);
        jSlider.setPaintTicks(true);
        jSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSliderStateChanged(evt);
            }
        });

        jPos.setFont(new java.awt.Font("Rockwell", 3, 14)); // NOI18N
        jPos.setText("Posición");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jButton8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jButton9)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jButton10)
                                        .addGap(43, 43, 43))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jButton11)
                                        .addGap(82, 82, 82)
                                        .addComponent(jButton12)
                                        .addGap(136, 136, 136))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn1Az)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn2Am)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn3Ro)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn4Ver)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn5Ro)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn6Am)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn7Az)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnConectar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnDesc, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(131, 131, 131)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(estado))
                        .addGap(18, 18, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(128, 128, 128)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPos)
                        .addGap(94, 94, 94)))
                .addComponent(jSlider, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jSlider, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jPos))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnConectar)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(estado)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(btnDesc)))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn1Az, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn2Am, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn3Ro, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn4Ver, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn5Ro, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn6Am, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn7Az, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton8)
                            .addComponent(jButton9)
                            .addComponent(jButton10))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton11)
                            .addComponent(jButton12))))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void poten() {

        //this.txtPos.setVisible(true);
        try {
            arduino.sendData("c");

        } catch (Exception ex) {
            Logger.getLogger(Interfaz.class.getName()).log(Level.SEVERE, null, ex);
        }

    }


    private void btn1AzActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1AzActionPerformed
        try {
            arduino.sendData("1");
            btn1Az.setEnabled(false);
        } catch (Exception ex) {
            Logger.getLogger(Interfaz.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn1AzActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        try {
            arduino.sendData("a");

            btn1Az.setEnabled(true);
            btn2Am.setEnabled(true);
            btn3Ro.setEnabled(true);
            btn4Ver.setEnabled(true);
            btn5Ro.setEnabled(true);
            btn6Am.setEnabled(true);
            btn7Az.setEnabled(true);

        } catch (Exception ex) {
            Logger.getLogger(Interfaz.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton12ActionPerformed

    private void btn2AmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2AmActionPerformed
        // TODO add your handling code here:
        try {
            arduino.sendData("2");
            btn2Am.setEnabled(false);
        } catch (Exception ex) {
            Logger.getLogger(Interfaz.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btn2AmActionPerformed

    private void btn3RoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3RoActionPerformed
        // TODO add your handling code here:
        try {
            arduino.sendData("3");
            btn3Ro.setEnabled(false);
        } catch (Exception ex) {
            Logger.getLogger(Interfaz.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn3RoActionPerformed

    private void btn4VerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4VerActionPerformed
        // TODO add your handling code here:
        try {
            arduino.sendData("4");
            btn4Ver.setEnabled(false);
        } catch (Exception ex) {
            Logger.getLogger(Interfaz.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn4VerActionPerformed

    private void btn5RoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn5RoActionPerformed
        // TODO add your handling code here:
        try {
            arduino.sendData("5");
            btn5Ro.setEnabled(false);
        } catch (Exception ex) {
            Logger.getLogger(Interfaz.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn5RoActionPerformed

    private void btn6AmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn6AmActionPerformed
        // TODO add your handling code here
        try {
            arduino.sendData("6");
            btn6Am.setEnabled(false);
        } catch (Exception ex) {
            Logger.getLogger(Interfaz.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn6AmActionPerformed

    private void btn7AzActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn7AzActionPerformed
        // TODO add your handling code here:
        try {
            arduino.sendData("7");
            btn7Az.setEnabled(false);
        } catch (Exception ex) {
            Logger.getLogger(Interfaz.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btn7AzActionPerformed

    private void btnConectarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConectarActionPerformed
        // TODO add your handling code here:
        conectar();
    }//GEN-LAST:event_btnConectarActionPerformed

    private void btnDescActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDescActionPerformed
        // TODO add your handling code here:
        desconectar();
    }//GEN-LAST:event_btnDescActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed

        try {
            arduino.sendData("8");
        } catch (Exception ex) {
            Logger.getLogger(Interfaz.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        try {
            arduino.sendData("b");
        } catch (Exception ex) {
            Logger.getLogger(Interfaz.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed

        try {
            arduino.sendData("9");
        } catch (Exception ex) {
            Logger.getLogger(Interfaz.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed

        try {
            arduino.sendData("0");
        } catch (Exception ex) {
            Logger.getLogger(Interfaz.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jButton10ActionPerformed

    private void jSliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSliderStateChanged

        jPos.setText("Nivel: " + jSlider.getValue());
        Led();
        try {
            arduino.sendData(String.valueOf(r));
        } catch (Exception ex) {
            Logger.getLogger(Interfaz.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jSliderStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn1Az;
    private javax.swing.JButton btn2Am;
    private javax.swing.JButton btn3Ro;
    private javax.swing.JButton btn4Ver;
    private javax.swing.JButton btn5Ro;
    private javax.swing.JButton btn6Am;
    private javax.swing.JButton btn7Az;
    private javax.swing.JButton btnConectar;
    private javax.swing.JButton btnDesc;
    private javax.swing.JLabel estado;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jPos;
    private javax.swing.JSlider jSlider;
    // End of variables declaration//GEN-END:variables

    @Override
    public void serialEvent(SerialPortEvent evento) {
        try {
            if (evento.getEventType() == SerialPortEvent.DATA_AVAILABLE) {
                DataInputStream lectura = new DataInputStream(puertoUSB.getInputStream());
                if (lectura.available() > 0) {
                    int valor = lectura.read();
                    if (valor == 50) {
                        JOptionPane.showMessageDialog(this, "Hay una peticion desde Arduino");
                    }
                }

            }
        } catch (Exception erro1) {
            erro1.printStackTrace();
        }
    }
}
